### ISSUE TITLE
Feature Request: Overlay Support

### ISSUE THREAD

**Issue by ulucs** [zaksabeast/CaptureSight#16]
Supporting overlays could be a great option for keeping players from returning to home menu every time they want to check CaptureSight, and save a lot of time. 

There are currently two libraries that work with overlays: 

https://github.com/3096/luxray/
https://github.com/WerWolv/libtesla/

From a first look into them, here's what I think their pros and cons are:

### Libtesla
✔ Actually a library, akin to Plutonium
✔ Should be simpler to port ui to
✖ Has some strong restrictions on memory
✖ Doesn't actually display on overlay, but a quick-menu

### Luxray
✔ Actually an overlay, you can play the game while it does its job
✔ Less restrictions on memory
✔ Has CaptureSight features planned, so the dev might contribute
✔ The overlay and app logic are decoupled, which is architecturally nice
✖ However, this might mean having to port app logic to a system kip
✖ Not actually a library, we have to draw the whole ui ourselves

If this feature would be nice to have, I think trying a libtesla port is currently within my capabilities and I'd like to try making this work (given the libtesla memory restriction lets me).

**Comment by zaksabeast** [comment]
This has been a requested feature, so it's something that will happen.  I also have a list of thoughts:

### Libtesla
- Works similar to Plutonium, which is what CaptureSight's applet uses, so it'll be easier for people to contribute to CaptureSight's applet and overlay
- One consistent way for users to interact with overlays
- Unless a better option comes, it'll probably be adopted over time by the community (both devs and users)
- From a UX perspective, it's better to have one tool managing all overlays
- Someone else is maintaining the overlay layer
- It is more of a quick-menu type, but I'm hopeful this will be modified

### Luxray (uses [lvgl](https://github.com/littlevgl/lvgl) under the hood)
- I pulled some of Luxray's overlay abilities into a library [on a fork](https://github.com/zaksabeast/luxray/tree/overlay-library) (it's a rough job right now but does work), so a bit of the overlay specific part is already handled
- More customizable, although this means more to setup
- It's been out for much longer and has a far larger community around it
- Luxray uses a custom lvgl fork, which needs to be maintained

I have a WIP version of CaptureSight using libtesla that I'm hoping to do a pre-release with and get feedback on - https://twitter.com/zaksabeast/status/1224181976795578370

I started making the overlay version of CaptureSight using the luxray overlay library, and libtesla happened to be released that same day.  This was great since it gave me a chance to try libtesla and have a fresh dev experience comparison in my mind.  I'm still not opposed to switching to the luxray overlay, but I am currently leaning towards libtesla.

**Comment by zaksabeast** [comment]
With the CaptureSight ovleray pre-release and the code now merged to master, I'm going to close this issue.
