### ISSUE TITLE
Shiny Frame 0 error

### ISSUE THREAD

**Issue by greenDarkness** [zaksabeast/CaptureSight#22]
When checking raid seeds via trade in the event that a shiny frame is +10,000, CaptureSight says that it is 0. If this is intentional, could the symbol be changed to an "x" or something similar as to not be confused when the shiny frame is actually 0?
Thanks for all your work on CaptureSight!

https://cdn.discordapp.com/attachments/405591144995749891/675950022407225361/20200209_000833.jpg

**Comment by zaksabeast** [comment]
This is not intentional.  Thanks for the bug report!

**Comment by greenDarkness** [comment]
No worries. Glad to contribute to the bettering of the application!

**Comment by zaksabeast** [comment]
Fixed with https://github.com/zaksabeast/CaptureSight/commit/dd64b8edabec5aa818cddd2211ef158a389447d7.

Additionally, https://github.com/zaksabeast/CaptureSight/commit/8ce8090f95d78556e0abe54f8a17a4b236f6c89a modified the display value of shiny frames over 9,999 frames to be "10K+" so it's clearer those shinies are over 10,000 frames away.

**Comment by greenDarkness** [comment]
Looking forward to the next release! Thanks Zaksabeast!
