### ISSUE TITLE
Need help adding translations

### ISSUE THREAD

**Issue by zaksabeast** [zaksabeast/CaptureSight#49]
CaptureSight's applet strives to be available in multiple languages.  With the applet rewrite, all the current translations are invalid, and I would really appreciate it if anyone wanted to contribute translations for the app.

## How to contribute

1. Please translate all of the below text
2. Provide the translations using one of the following methods:
   - Comment in this issue with the translations (you will be credited in the commit message that adds the translations)
   - Make a pull request with your translations (translations belong in `CaptureSight-Applet/romfs/i18n/<language code>.json`)

## Phrases to translate

Don't worry about attacks, abilities, natures, Pokemon species, etc.

Words to translate:
- Active dens
- Advances to next shiny
- All dens
- Continue
- EVs
- Find raid seed
- Misc
- Move 1
- Move 2
- Move 3
- Move 4
- Moves
- Multiplier
- Note: This will take a lot of time and cannot be used on shiny or event Pokemon. The console will appear frozen while searching (this will be fixed in the future).
- Raid
- Raid Seed
- Press A to view raid seed
- Seed found:
- Shiny type:
- Trade
- Weaknesses
- Weakness
- Wild
- Wild/Raid/Trade
- Egg cycles
- OT Gender
- Male
- Female
- Genderless
- Misc Pokemon
- Party Pokemon
- Box Pokemon
- Party
- Shiny
- Star
- Square
- Event
- Nature
- Minted Nature
- Ability
- Friendship
- EC
- PID
- IVs
- HP
- ATK
- DEF
- SPA
- SPD
- SPE

If you have any questions about context or intent of the wording, please comment with questions!

**Comment by Real96** [comment]
Active dens = Tane attive
Advances to next shiny = Avanza fino al prossimo cromatico
All dens = Tutte le tane
Continue = Continua
EVs
Find raid seed = Trova il Seed del Raid
Misc = Generale
Move 1 = Mossa 1
Move 2 = Mossa 2
Move 3 = Mossa 3
Move 4 = Mossa 4
Moves = Mosse
Multiplier = Moltiplicatore

Note: This will take a lot of time and cannot be used on shiny or event Pokemon. The console will appear frozen while searching (this will be fixed in the future).
=
Nota: Questo impiegherà molto tempo e non può essere usato per la cromaticità o per i Pokemon evento. La console sembrerà bloccata durante la ricerca (questo sarà sistemato in futuro) 

Raid
Raid Seed = Seed del Raid
Press A to view raid seed = Premi A per vedere il seed del raid
Seed found: = Seed trovato:
Shiny type: Tipo di cromaticità:
Trade = Scambio
Weaknesses = Debolezze
Weakness = Debolezza
Wild = Selvatico
Wild/Raid/Trade = Selvatico/Raid/Scambio
Egg cycles = Cicli uovo
OT Gender = Sesso dell'AO
Male = Maschio
Female = Femmina
Genderless = Sconosciuto
Misc Pokemon = Pokemon Generale
Party Pokemon = Pokemon in squadra
Box Pokemon = Pokemon nei box
Party = Squadra
Shiny = Cromatico
Star = Stella
Square = Quadrato
Event = Evento
Nature = Natura
Minted Nature = Natura modificata (Menta)
Ability = Abilità
Friendship = Amicizia
EC
PID
IVs
HP
ATK
DEF
SPA
SPD
SPE

**Comment by zaksabeast** [comment]
I'm going to close this since the rewrite doesn't have i18n features.  If anything is localized in the future, it will probably just be game content, such as Pokemon, moves, and abilities.
