### ISSUE TITLE
Buttons not working when in applet mode

### ISSUE THREAD

**Issue by Robertb36** [zaksabeast/CaptureSight#53]
I'm using ReiNX because I can't seem to find any "legal and unmodified" dlc's anywhere, so I can't use the overlay and when using Capturesight in applet mode, it doesn't seem to recognise the buttons. Downloaded via HB App Store with Atmosphere 0.14.1 and ReiNX 3.0 and hekate 5.3 (I believe.) I know that ReiNX is dead and unsupported, but atmosphere doesn't seem to like Tinfoil or Awoo Installer and just claims that the apps are corrupted.

**Comment by zaksabeast** [comment]
Hello!

Thanks for taking the time to open an issue :slightly_smiling_face: 

Supporting custom firmware outside of the latest Atmosphere and switch version isn't feasible for a number of reasons:
- Vital pieces of CaptureSight rely on Atmosphere-only features
- Inputs in CaptureSight are handled by Tesla and Borealis, which might not support outdated or non-Atmosphere custom firmwares
- I don't have a switch with older firmware versions to test on, so I don't have the ability to develop and test for older firmware versions

Sadly this means I won't be able to help get CaptureSight running on ReiNX.  Since CaptureSight runs well on Atmosphere 0.14.1, I'm going to close the issue.

Sorry more help couldn't be provided!
