### ISSUE TITLE
Report Dynamax Adventure SEED Issue: 9eb313ab4afb2ad8

### ISSUE THREAD

**Issue by Th3Alic3** [zaksabeast/CaptureSight#63]
Hey!!!

Boss: Landorus
NPCs: 3
SEED: 9eb313ab4afb2ad8

![image](https://user-images.githubusercontent.com/57371173/98591311-e5b7fd80-2284-11eb-9360-bafd93b24d2d.png)

Round 1: Electric / Normal (Ditto)
Round 2: ? / ? / Normal (Linoone Galar) / ?
Round 3: Electric / Fire (Heatmor) / Steel / Normal

_(SEE!!! Not enough to time to record down details before that timer finishes.)_

**Comment by Th3Alic3** [comment]
![image](https://user-images.githubusercontent.com/57371173/98591924-cff70800-2285-11eb-8c1a-0e275bc0c9e9.png)

Ditto was Round 1 / Slot 2... definitely not Round 2! No Kingler or Xatu in Round 1.

**Comment by zaksabeast** [comment]
Thank you for the report.

> (SEE!!! Not enough to time to record down details before that timer finishes.)

There are a few times that might be easier to take screenshots:
- During battle animations there's a decent amount of time before the next attack needs to be selected
- After defeating the boss or losing the adventure, but before exiting the adventure.  This screen doesn't have a timer, and the save seed will still be the same

An easy way to write down the types of the dmax adventure is to use the switch's video record feature to get a video of the dungeon as you're scrolling through it.  The video is a great way to write down types at your own pace since it can be viewed after the adventure and paused as needed.

> (It would really help if the app listed the Round / Slot # for the mons.)

I like this idea!

**Comment by Th3Alic3** [comment]
Please close this post and refer to: #67
