### ISSUE TITLE
try to use cargo build-std instead

### ISSUE THREAD

**Issue by ca1e** [zaksabeast/CaptureSight#82]
https://github.com/zaksabeast/CaptureSight/blob/ff0ba30fb10b7dce9cda02701febdbe2b5b3577f/libs/csight-core/Cargo.toml#L13

Im very new to rust, but is it(no_std_io) as same as the cargo build-std?

If so, we can use cargo build-std instead since rust 1.58 released
see also: https://github.com/aarch64-switch-rs/nx/blob/master/.cargo/config.toml

**Comment by zaksabeast** [comment]
Hey there! :wave:  Thanks for your interest in CaptureSight.

[no_std_io](https://github.com/zaksabeast/no_std_io) is a small library I wrote to work with data in no_std environments, but isn't related to project configuration.

The standard library has several smaller crates, including (but not limited to) [core](https://doc.rust-lang.org/core/) and [std](https://doc.rust-lang.org/std/).

[no_std](https://docs.rust-embedded.org/book/intro/no-std.html) tells the crate to link with core and not std.  Core is dependency free and will be usable on any target rust can be compiled to.  std includes code that is specific to the target.  To my knowledge, no one has gotten std to work on the switch, which is one reason why switch projects use core.

[build-std](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std-features) allows us to configure what goes into the standard library we use.  The example you linked includes `core`, `compiler_builtins`, and `alloc`.

[Capturesight uses build-std too!](https://github.com/zaksabeast/CaptureSight/blob/d2bed41a205cbe81bb011d8df248e582ae4365af/libs/csight-core/Makefile#L4)  However CaptureSight should move it to `.config/cargo.toml` as well since that's the proper location.

**Comment by ca1e** [comment]
Thank you for your reply, I understand a little better now! Thanks  for writing such a useful tool!(both no-std-io and CaptureSight)
