### ISSUE TITLE
CS Not loading any data

### ISSUE THREAD

**Issue by xxsytriskxx** [zaksabeast/CaptureSight#85]
First time using the CS overlay but unfortunately it doesn't seem to be reading my Pokemon Shield data while in-game. I'm running the following:

tesla nxovlloader v1.0.6
CaptureSight v0.11.0
Pokemon Shield v.1.3.2
Atmosphere v1.2.6
Switch v13.2.1

Screenshots below:
![WhatsApp Image 2022-02-04 at 4 48 19 PM (2)](https://user-images.githubusercontent.com/20542113/152531828-e4f18527-6d8e-4021-9a6e-ce08b153ff58.jpeg)
![WhatsApp Image 2022-02-04 at 4 48 19 PM](https://user-images.githubusercontent.com/20542113/152531840-44a818e0-094e-4103-9b7d-a2eff4496be2.jpeg)
![WhatsApp Image 2022-02-04 at 4 48 18 PM](https://user-images.githubusercontent.com/20542113/152531843-169d61b1-d9c1-45ec-9c86-e6f87bb185c3.jpeg)
![WhatsApp Image 2022-02-04 at 4 48 19 PM (1)](https://user-images.githubusercontent.com/20542113/152531847-4d011417-302f-4251-b81f-e1667d2ed41a.jpeg)

I don't believe I'm running any sysmodules, so I'm unsure what's causing this issue.

**Comment by zaksabeast** [comment]
Hello!  Sorry to hear about the troubles, and thank you for all of the extra info.  You've already answered most questions I normally start with and have added screenshots.

A few more questions that might help debug the problem:
- Is csight able to show any information?
- Can Edizon show Shield cheats (you don't need to enable them) at the same time csight is not showing info?
- You mentioned not currently running sysmodules, but have you ever used sysmodules, including sysbotbase?

**Comment by xxsytriskxx** [comment]
Thanks for getting back to me! To answer your questions:

- When I was first setting it up, the overlay wasn't working like in the screenshots but once during the 20 something times I attempted a game/console restart it actually loaded the gamedata. I was able to see my Party info, Active dens, Trainer Id, etc. I have no idea what triggered it to work but to answer your question **it did show information that one time**.
- Edizon is showing the cheats. I haven't tested whether they work or not though.
- I mentioned it because after looking here on github and on the RNG Discord, I saw talk about some sysmodules might be interfering with CS. I can confirm I didn't have sys-botbase or usb-botbase installed when I made this thread yesterday (I just recently added sys-botbase today for PLA coincidentally enough, but of course still no changes with CS and my Shield game.

On that last point, when I did try to open CS while running Arceus I would get the error "Game not supported" or something along those lines. No clue why, I assume its because the game isn't running on a cartridge?

**Comment by zaksabeast** [comment]
Csight uses atmosphere's dmnt:cht, same as Edizon.  If Edizon can read cheats it means it has access to dmnt:cht, and csight should too.  Csight should show an error if it doesn't, but I had to ask just to rule it out.

I asked about sysbotbase since it interferes with dmnt:cht (and csight by extension).  When testing csight, keep in mind that using sysbotbase before using csight will almost guarantee csight won't work (and vice versa).  You'll want to restart your console and not use sysbotbase before testing csight again.

Another thought that some people have encountered: some people restart the game, but don't restart csight, which causes csight to read from incorrect places in memory.  After restarting a game, try pressing "B" enough times to exit csight and close tesla.  Touching the screen and using the button combo only hides csight, it doesn't restart it.  Pressing "B" to fully exit is the only way to make sure csight loads data properly between game restarts.

> On that last point, when I did try to open CS while running Arceus I would get the error "Game not supported" or something along those lines. No clue why, I assume its because the game isn't running on a cartridge?

Arceus support was added after 0.11.0.  You can grab a build from [the actions page](https://github.com/zaksabeast/CaptureSight/actions) which hosts a temporary build after every commit (these may not be stable), or [the releases page](https://github.com/zaksabeast/CaptureSight/releases) for the pre-release with Arceus support (these will be stable).  Keep in mind that Arceus support is very basic and is in need of updates.

**Comment by xxsytriskxx** [comment]
Thanks to your feedback and input I was able to figure out my issue. I had something called SaltySD installed on my SD card, once I located its files and removed them then rebooted my switch, CS started working again!

Really appreciate your prompt response! 

PS - Sorry I misread and thought the basic Arceus support was v11 not v12. Will wait for the stable release in the meantime, thanks again!

**Comment by zaksabeast** [comment]
I'm glad the issue was solved!

The pre-release will be stable in the sense that you can expect it to not crash; it just needs a better way to show data.  However waiting for a proper release works too.

Enjoy!
