### ISSUE TITLE
Support for 16.0.0

### ISSUE THREAD

**Issue by no2moloh** [zaksabeast/CaptureSight#97]
The new update has broken almost all of the plugins within Tesla.

**Comment by zaksabeast** [comment]
Thanks for the issue.  For visibility, below is my release plan.

[ovl-sysmodules](https://github.com/WerWolv/ovl-sysmodules) and [Tesla-Menu](https://github.com/WerWolv/Tesla-Menu) had compatibility updates within the past few hours.  I'm waiting on those to release first since people won't be able to use csight until then, and I want to test csight with the same tool releases people will be using.

The libnx PR, https://github.com/switchbrew/libnx/pull/603, says it's not ready to merge yet.  Ideally libnx also has a release to support 16.0.0, but it's not strictly necessary.

Once ovl-sysmodules and Tesla-Menu are good to go, I'll get a csight release up.

**Comment by lowburger** [comment]
Hi, Tesla-Menu and ovl-sysmodules have auto build on repo. You could now do release? Thx!

**Comment by zaksabeast** [comment]
CaptureSight has been updated for 16.0.0!  Please grab the latest release from the releases page: https://github.com/zaksabeast/CaptureSight/releases
